app:
  user:
    username: ${APP_USER_USERNAME}
    password: ${APP_USER_PASSWORD}
    roles: ROLE_ADMIN
  jwt:
    secret: ${JWT_SECRET}
    expiration:
      ms : 1800000

spring:
  application:
    name: app
  config :
    activate :
      on-profile: local

  datasource :
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    jpa :
      hibernate :
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always