app:
  user:
    username: ${APP_USER_USERNAME}
    password: ${APP_USER_PASSWORD}
    roles: ROLE_ADMIN
  jwt:
    secret: ${JWT_SECRET}
    expiration:
      ms : 1800000

spring:
  profiles : docker
  application:
    name: app

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always