services:
  # Spring Boot Backend
  app:
    # Use the image that was built by the GitHub Actions workflow
    # This assumes the image 'spring-boot-app-image:latest' is available
    image: spring-boot-app-image:latest
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:

      SPRING_PROFILES_ACTIVE : docker

      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      APP_USER_USERNAME: ${APP_USER_USERNAME}
      APP_USER_PASSWORD: ${APP_USER_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my-app-network

  front:
    # If the frontend is not needed for OpenAPI doc generation, you could remove it
    # to speed up the workflow.
    build:
      context: ../front
      dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "4200:4200"
    volumes:
      - ../front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - my-app-network
    depends_on:
      - app

  # PostgreSQL DB
  db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-app-network
    ports:
      - "3000:3000"

networks:
  my-app-network:
    driver: bridge

volumes:
  db_data: