name: CD Deploy

on:
  workflow_run:
    workflows: ["Terraform Apply"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DO_VM_HOST }}
          username: ${{ secrets.DO_VM_USER }}
          key: ${{ secrets.DO_VM_SSH_KEY }}
          script: |
            cd /app
            git pull origin main
            docker compose pull
            docker compose up -d
