name: CD Backend

on:
  workflow_run:
    workflows: ["Backend Security Scans"]
    types: [completed]

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: CD Placeholder
        run: echo "CD deploy placeholder"