name: CD Frontend

on:
  workflow_run:
    workflows: ["CI Frontend"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Placeholder
        run: echo "CD deploy placeholder for frontend"
