name: CI Frontend

on:
  push:
    branches: ["**"]
    paths:
      - 'front/**'
      - '.github/workflows/**'
  pull_request:
    branches: [main]


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: false
          cache-dependency-path: 'front/package-lock.json'

      - name: Install dependencies
        working-directory: front
        run: npm ci --verbose
      
      - name: Build app
        working-directory: front
        env:
          CI: false  
        run: npm run build

      - name: Run tests
        working-directory: front
        run: npm test -- --watchAll=false --ci --runInBand

      - name: Build Docker image
        run: docker build -t frontend-app:latest -f front/Dockerfile front

      - name: Save Docker image as artifact 
        uses: actions/upload-artifact@v4
        with:
          name: frontend-image
          path: |
            $(docker save frontend-app:latest | gzip > frontend-app.tar.gz)

  build-and-push-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_tag: ${{ steps.meta.outputs.image_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define Image Tag
        id: meta
        run: echo "image_tag=ghcr.io/${{ github.repository_owner }}/react-frontend:${{ github.sha }}-staging" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: front
          push: true
          tags: ${{ steps.meta.outputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  security-scans:
    uses: ./.github/workflows/security-scans.yaml
    needs: [build-and-test, build-and-push-docker]
    with:
      image_tag: ${{ needs.build-and-push-docker.outputs.image_tag }}