name: Policy Check

on:
  pull_request:
    paths:
      - 'terraform/**'

jobs:
  opa-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest

      - name: Terraform Plan
        run: terraform -chdir=terraform plan -out=tfplan.binary

      - name: Convert Plan to JSON
        run: terraform show -json terraform/tfplan.binary > plan.json

      - name: Run OPA
        run: opa eval --format pretty --fail-defined -i plan.json -d policy/ "data.terraform.security.deny"
