name: Generate & Deploy OpenAPI Docs

on:
  push:
    branches:
      - features/back

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest

    steps:
      # Clone your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Java and build your Spring Boot app
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Spring Boot app
        run: ./mvnw clean package -DskipTests=true

      - name: Run app
        run: java -jar target/*.jar &
      
      - name: Wait for API to be ready
        run: sleep 15

      - name: Export OpenAPI YAML
        run: |
          curl http://localhost:8080/v3/api-docs.yaml -o swagger-ui/openapi.yaml

      - name: Lint with Spectral
        run: |
          npm install -g @stoplight/spectral-cli
          spectral lint swagger-ui/openapi.yaml

      - name: Lint with Redocly CLI
        run: |
          npm install -g @redocly/cli
          redocly lint swagger-ui/openapi.yaml

      - name: Deploy Swagger UI to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./swagger-ui
          publish_branch: gh-pages
